version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: url_shortener_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: django_app
    restart: always
    depends_on:
      - db
      - redis
    environment:
      SQL_ENGINE: django.db.backends.postgresql
      SQL_DATABASE: url_shortener_db
      SQL_USER: admin
      SQL_PASSWORD: admin123
      SQL_PORT: 5432
      DEBUG: "True"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"

  worker:
    build: .
    container_name: celery_worker
    restart: always
    depends_on:
      - web
      - redis
    environment:
      SQL_ENGINE: django.db.backends.postgresql
      SQL_DATABASE: url_shortener_db
      SQL_USER: admin
      SQL_PASSWORD: admin123
      SQL_PORT: 5432
      DEBUG: "True"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    command: celery -A valify_task worker --loglevel=info

volumes:
  postgres_data:
